# Generated by Django 5.0.6 on 2024-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_code_skill",
            field=models.BooleanField(default=True),
        ),
    ]
