# Generated by Django 5.0.6 on 2024-05-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_skill_is_code_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="certificate"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="is_code_skill",
            field=models.BooleanField(default=False),
        ),
    ]
