# Generated by Django 5.0.6 on 2024-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_certificate_image_alter_skill_is_code_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactprofile",
            name="phone",
            field=models.SmallIntegerField(null=True, verbose_name="Phone Number"),
        ),
    ]
