# Generated by Django 5.0.6 on 2024-06-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_contactprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="link",
            field=models.URLField(default=True),
        ),
    ]
