# Generated by Django 5.0.6 on 2024-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_portfolio_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="link",
            field=models.URLField(default=True, max_length=300, null=True),
        ),
    ]
